### ISSUE TITLE
Check plugin status when API request

### ISSUE THREAD

**Issue by jojotong** [kubegems/kubegems#138]
Kubegems service maybe need a cache to store each plugin's status.

So service can check related plugin status on each api request, Not only front-end to check the plugin status.

**Comment by LinkMaq** [comment]
Any further updates? @cnfatal

**Comment by jojotong** [comment]
我的想法是:
1. service 在内存中维护一个map 缓存所有集群的插件状态
2. 前端启停插件统一走service,此处修改map（目前直接走的agent）
3. service定时(30s ?) 遍历所有集群插件，同时更新map. (避免后台启停插件时无感知)

@cnfatal @LinkMaq @pepesi

**Comment by cnfatal** [comment]
> 哦，就是调插件的接口时，统一判断是否启用，加个middlewire

每个集群插件状态都不一样。一个接口可以通向不同集群。而且增加缓存这件事还会带来更多未知问题。现在前端已经根据插件状态做了判断，后段暂时可以不用再判断。这个功能的收益并不大，暂时关闭。
