### ISSUE TITLE
Enable GPU Metrics

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#158]
**Is your feature request related to a problem? Please describe.**
we should scape gpu device metrics，used to show the resources usage for pod

**Describe the solution you'd like**
NVIDIA offers a solution called `DCGM-Exporter`，we can integrate it  as a plugin into kubegems which like `node-exporter`

We expect to be able to provide each container which scheduling a gpu has its own independent resource metrics. 

https://docs.nvidia.com/datacenter/cloud-native/gpu-telemetry/dcgm-exporter.html#gpu-telemetry

**Comment by jojotong** [comment]
In which version is this plugin planned to be released? v1.21.1 or v1.22.0 @LinkMaq

**Comment by jojotong** [comment]
This feature may be more suitable release in v1.22.0

**Comment by LinkMaq** [comment]
Pod GPU utilization (in %).
```
- record: gems_container_gpu_usage_percent
   expr: |
     DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION
```
PodGPU Memory (in MB).
```
- record: gems_container_gpu_memory_usage_ millionbytes
   expr: |
     sum(DCGM_FI_DEV_FB_USED * on(namespace,pod) group_left(node,host_ip,pod_ip) gems_pod_status) 
     by (pod,namespace,device,node,host_ip,pod_ip,modelName)
```
PodGPU temperature (in C).
```
- record: gems_container_gpu_usage_temp
   expr: |
     sum(DCGM_FI_DEV_GPU_TEMP * on(namespace,pod) group_left(node,host_ip,pod_ip) gems_pod_status) 
     by (pod,namespace,device,node,host_ip,pod_ip,modelName)
```
PodGPU Power (in C).
```
- record: gems_container_gpu_usage_power
   expr: |
     sum(DCGM_FI_DEV_POWER_USAGE * on(namespace,pod) group_left(node,host_ip,pod_ip) gems_pod_status) 
     by (pod,namespace,device,node,host_ip,pod_ip,modelName)
```

**Comment by jojotong** [comment]
>     by (pod,namespace,device,node,host_ip,pod_ip,modelName)
Lost `container` label.

**Comment by jojotong** [comment]
- gems_container_gpu_usage_percent: GPU 使用率 [percent-1-100]
- gems_container_gpu_memory_usage_mb: GPU 显存使用量 [byte-MB]
- gems_container_gpu_temp: GPU温度 [°C]
- gems_container_gpu_power_usage_watt: GPU功率 [W(瓦特)]

@chenshunliang
