### ISSUE TITLE
Apiserver version incorrect

### ISSUE THREAD

**Issue by jojotong** [kubegems/kubegems#162]
**What did you do?**
After upgrade k8s version from 1.18 to 1.20, and then watch apiserver version in cluster detail.

**What did you expect to see?**
k8s version show 1.20

**What did you see instead? Under which circumstances?**
![image](https://user-images.githubusercontent.com/100849526/180024330-e19150be-10d6-41b6-a574-19d5faf7b237.png)

**Environment**

* Kubegems version:

v1.21.0

* Kubernetes version:
v1.20.15

**Comment by LinkMaq** [comment]
Using the synchronous interface to collect kubernetes versions can cause a bucket effect  on cluster list api. 
We need to handle it in the kubegems worker with an asynchronous call，and then write to db.

**Comment by LinkMaq** [comment]
Any further updates?

**Comment by jojotong** [comment]
No, fixed.
