### ISSUE TITLE
Support initcontainer logs

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#165]
**Is your feature request related to a problem? Please describe.**
pod  can't view initcontainer logs, this feature is essential.

**Comment by chenshunliang** [comment]
this enhancement commited at https://github.com/kubegems/dashboard/commit/a826e8691172925ad5c4072a19f0e58bdc45d14e

**Comment by LinkMaq** [comment]
> this enhancement commited at [kubegems/dashboard@a826e86](https://github.com/kubegems/dashboard/commit/a826e8691172925ad5c4072a19f0e58bdc45d14e)

👏🏻
