### ISSUE TITLE
Enable files download from pod 

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#169]
**Is your feature request related to a problem? Please describe.**
Many users expect to be able to download files from the container directly from the page. Often these contain logs, configuration or other program-related files.

This is a very useful feature, and perhaps we can replicate it on kubegems by referring to the `kubectl cp` command.

**Describe the solution you'd like**

Add a button to download a file to the container terminal page of kubegems, click the button and download the file by filling in the absolute path to the file in the container.

**Comment by LinkMaq** [comment]
Any further updates? @pepesi

**Comment by pepesi** [comment]
currently, single file download is supported,  and `base64` is required in the target container

something need to consider:
1. should support downloading a directory as tgz (like kubectl do)?
2. file size limit?

**Comment by pepesi** [comment]
https://github.com/kubegems/kubegems/pull/253 merged
