### ISSUE TITLE
Explicitly mark Pod that use GPU devices

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#170]
**Is your feature request related to a problem? Please describe.**
If enable  `nvidia-device-plugin` or `tke-gpu-manager` on kubegems plugins management page ,we should mark a plugin icons which pod used gpu devices. this feature just like nodes which enabled gpu.

**Comment by LinkMaq** [comment]
Any further updates? @chenshunliang

**Comment by chenshunliang** [comment]
This feature is merged in v1.22.0-beta.0 .
