### ISSUE TITLE
Can't view logs when pod on "error" state

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#176]
**What did you do?**
i can't open logs when my containers on `error` state
<img width="808" alt="image" src="https://user-images.githubusercontent.com/2688646/182281527-91b85716-5d5d-4057-8314-59a9a147ff58.png">

**What did you expect to see?**

what ever state container after started ,we should view container's log

**Environment**

* System information:

	ubuntu20.04

* Kubegems version:

	v1.21

* Kubernetes version:

	v1.23.8

**Comment by LinkMaq** [comment]
Any further updates? @chenshunliang

**Comment by chenshunliang** [comment]
This feature is merged in v1.22.0-beta.0 .
