### ISSUE TITLE
【Dashboard】在点击”服务调用图“后页面一直处于”数据获取中...“

### ISSUE THREAD

**Issue by shuhanghang** [kubegems/kubegems#184]
未安装istio插件。点击进入“项目环境->服务治理->虚拟空间->环境空间->服务调用图”后页面一直处于数据获取中，只能后退否则无法进行其他操作

**Comment by chenshunliang** [comment]
Thanks for your bug issue. This bug was fixed at https://github.com/kubegems/dashboard/pull/312
