### ISSUE TITLE
Does this project depend on the operator-sdk?

### ISSUE THREAD

**Issue by Answerlord** [kubegems/kubegems#220]

**Comment by Answerlord** [comment]
I recently studied operator-sdk, and then I found your project, which is a great project. I looked at the source code and found that the code structure is similar to that of operator-sdk, but not completely the same. Is this a project based on operator-sdk?

**Comment by cnfatal** [comment]
No,but not completely.  we both use kubebuilder for CRD/RBAC generation; The code structure is a convention of all k8s operator(controller) not exclusive to the operator sdk.

Operator-sdk-go is just a scaffold to quickly start a operator which provided an OOTB environment (include code-gen controller-gen ,Makefile,envtest ) , it is not suitable for us now, our repository is more complex then a pure operator.

What do you want to do with Oprator-sdk on this project?

**Comment by Answerlord** [comment]
> No,but not completely. we both use kubebuilder for CRD/RBAC generation; The code structure is a convention of all k8s operator(controller) not exclusive to the operator sdk.
> 
> Operator-sdk-go is just a scaffold to quickly start a operator which provided an OOTB environment (include code-gen controller-gen ,Makefile,envtest ) , it is not suitable for us now, our repository is more complex then a pure operator.
> 
> What do you want to do with Oprator-sdk on this project?

Thanks for your answer!
I'm still at school and try to learn something about k8s network programming.I would like to add an organization function to your project(just for practice),but I had never touch this before,I don't know if the operator-sdk can do this,so I pull this issue.If you don't mind, please tell me what knowledge you need to understand your source code.

**Comment by LinkMaq** [comment]
Perhaps you could start by providing KubeGems with support for Kubernetes APIs, such as ServiceAccount, Role Policy, etc.
We are very welcom to submit a PR ! 💪
