### ISSUE TITLE
Unknown database 'kubegems' after install kubegems

### ISSUE THREAD

**Issue by wimmerX** [kubegems/kubegems#250]
**What did you do?**
Follow the document  installation(https://www.kubegems.io/docs/installation/quick-install)
**What did you expect to see?**
all kubegems pods running normally
**What did you see instead? Under which circumstances?**
![image](https://user-images.githubusercontent.com/57867911/191679990-25cc1c57-e5ad-4e11-b44e-30ebfdfc5fec.png)
**Environment**

* System information:
Linux 5.4.214-1.el7.elrepo.x86_64

* Kubernetes version:
k8s:1.22.5 calico:v3.24.1

* Kubegems version:
v1.21.4

* Logs:
kubectl -n kubegems logs [ALL CrashLoopBackOff Pods] output:
2022-09-22 07:02:31.906	warn	config/config.go:90	no config file found or config file format error: Config File "config" Not Found in "[/app /app/config]"
2022-09-22 07:02:31.907	info	config/config.go:107	config from env: APPSTORE_ADDR=http://kubegems-chartmuseum.kubegems:8080
2022-09-22 07:02:31.907	info	config/config.go:107	config from env: ARGO_ADDR=http://kubegems-argo-cd-server:80
2022-09-22 07:02:31.907	info	config/config.go:107	config from env: ARGO_PASSWORD=**********
2022-09-22 07:02:31.907	info	config/config.go:107	config from env: ARGO_USERNAME=admin
2022-09-22 07:02:31.907	info	config/config.go:107	config from env: GIT_ADDR=http://kubegems-gitea-http:3000
2022-09-22 07:02:31.907	info	config/config.go:107	config from env: GIT_PASSWORD=***************
2022-09-22 07:02:31.907	info	config/config.go:107	config from env: GIT_USERNAME=gitea_admin
2022-09-22 07:02:31.907	info	config/config.go:107	config from env: MYSQL_ADDR=kubegems-mysql-headless:3306
2022-09-22 07:02:31.907	info	config/config.go:107	config from env: MYSQL_PASSWORD=**********
2022-09-22 07:02:31.907	info	config/config.go:107	config from env: REDIS_ADDR=kubegems-redis-headless:6379
2022-09-22 07:02:31.907	info	config/config.go:107	config from env: REDIS_PASSWORD=**********
2022-09-22 07:02:31.907	info	log/log.go:19	logger level updated	{"level": "debug"}
2022-09-22 07:02:31.909	error	gorm@v1.21.15/gorm.go:202	failed to initialize database, got error Error 1049: Unknown database 'kubegems'
Error: Error 1049: Unknown database 'kubegems'
Error 1049: Unknown database 'kubegems'

**Comment by wimmerX** [comment]
![image](https://user-images.githubusercontent.com/57867911/191697471-1dae270c-06cb-4b81-816a-e15a0ca5dc30.png)
是有一个job失败了

**Comment by wimmerX** [comment]
> 看起来缺少了`kubegems-init-v1.21.4`这个 job，执行`kubectl get job -n kubegems` 看下输出呢

![image](https://user-images.githubusercontent.com/57867911/191697636-3ccd9c41-5861-4305-a3a7-a05eda8e7e4f.png)
是有一个job失败了

**Comment by LinkMaq** [comment]
看下 kubegems-init 这个 job 的日志呢

**Comment by wimmerX** [comment]
> 看下 kubegems-init 这个 job 的日志呢
Name:             kubegems-init-v1.21.4
Namespace:        kubegems
Selector:         controller-uid=cda35897-4161-4060-9ffd-317d6c8fdf4f
Labels:           app.kubernetes.io/component=kubegems
                  app.kubernetes.io/instance=kubegems
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=kubegems
                  helm.sh/chart=kubegems-1.21.0
Annotations:      batch.kubernetes.io/job-tracking: 
                  meta.helm.sh/release-name: kubegems
                  meta.helm.sh/release-namespace: kubegems
Parallelism:      1
Completions:      <unset>
Completion Mode:  NonIndexed
Start Time:       Thu, 22 Sep 2022 13:31:01 +0800
Pods Statuses:    0 Active (0 Ready) / 0 Succeeded / 1 Failed
Pod Template:
  Labels:  app.kubernetes.io/component=kubegems
           app.kubernetes.io/instance=kubegems
           app.kubernetes.io/managed-by=Helm
           app.kubernetes.io/name=kubegems
           controller-uid=cda35897-4161-4060-9ffd-317d6c8fdf4f
           helm.sh/chart=kubegems-1.21.0
           job-name=kubegems-init-v1.21.4
  Containers:
   mysql-init:
    Image:      registry.cn-beijing.aliyuncs.com/kubegems/kubegems:v1.21.4
    Port:       <none>
    Host Port:  <none>
    Args:
      service
      migrate
      --initdata=true
    Environment Variables from:
      kubegems-config  Secret  Optional: false
    Environment:
      MYSQL_PASSWORD:  <set to the key 'mysql-root-password' in secret 'kubegems-mysql'>  Optional: false
      REDIS_PASSWORD:  <set to the key 'redis-password' in secret 'kubegems-redis'>       Optional: false
      ARGO_PASSWORD:   <set to the key 'clearPassword' in secret 'argocd-secret'>         Optional: false
    Mounts:            <none>
  Volumes:             <none>
Events:                <none>

**Comment by wimmerX** [comment]
> 看下 kubegems-init 这个 job 的日志呢

Name:             kubegems-init-v1.21.4
Namespace:        kubegems
Selector:         controller-uid=cda35897-4161-4060-9ffd-317d6c8fdf4f
Labels:           app.kubernetes.io/component=kubegems
                  app.kubernetes.io/instance=kubegems
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=kubegems
                  helm.sh/chart=kubegems-1.21.0
Annotations:      batch.kubernetes.io/job-tracking: 
                  meta.helm.sh/release-name: kubegems
                  meta.helm.sh/release-namespace: kubegems
Parallelism:      1
Completions:      <unset>
Completion Mode:  NonIndexed
Start Time:       Thu, 22 Sep 2022 13:31:01 +0800
Pods Statuses:    0 Active (0 Ready) / 0 Succeeded / 1 Failed
Pod Template:
  Labels:  app.kubernetes.io/component=kubegems
           app.kubernetes.io/instance=kubegems
           app.kubernetes.io/managed-by=Helm
           app.kubernetes.io/name=kubegems
           controller-uid=cda35897-4161-4060-9ffd-317d6c8fdf4f
           helm.sh/chart=kubegems-1.21.0
           job-name=kubegems-init-v1.21.4
  Containers:
   mysql-init:
    Image:      registry.cn-beijing.aliyuncs.com/kubegems/kubegems:v1.21.4
    Port:       <none>
    Host Port:  <none>
    Args:
      service
      migrate
      --initdata=true
    Environment Variables from:
      kubegems-config  Secret  Optional: false
    Environment:
      MYSQL_PASSWORD:  <set to the key 'mysql-root-password' in secret 'kubegems-mysql'>  Optional: false
      REDIS_PASSWORD:  <set to the key 'redis-password' in secret 'kubegems-redis'>       Optional: false
      ARGO_PASSWORD:   <set to the key 'clearPassword' in secret 'argocd-secret'>         Optional: false
    Mounts:            <none>
  Volumes:             <none>
Events:                <none>

**Comment by wimmerX** [comment]
> > 看下 kubegems-init 这个 job 的日志呢
> 
> Name: kubegems-init-v1.21.4 Namespace: kubegems Selector: controller-uid=cda35897-4161-4060-9ffd-317d6c8fdf4f Labels: app.kubernetes.io/component=kubegems app.kubernetes.io/instance=kubegems app.kubernetes.io/managed-by=Helm app.kubernetes.io/name=kubegems helm.sh/chart=kubegems-1.21.0 Annotations: batch.kubernetes.io/job-tracking: meta.helm.sh/release-name: kubegems meta.helm.sh/release-namespace: kubegems Parallelism: 1 Completions: Completion Mode: NonIndexed Start Time: Thu, 22 Sep 2022 13:31:01 +0800 Pods Statuses: 0 Active (0 Ready) / 0 Succeeded / 1 Failed Pod Template: Labels: app.kubernetes.io/component=kubegems app.kubernetes.io/instance=kubegems app.kubernetes.io/managed-by=Helm app.kubernetes.io/name=kubegems controller-uid=cda35897-4161-4060-9ffd-317d6c8fdf4f helm.sh/chart=kubegems-1.21.0 job-name=kubegems-init-v1.21.4 Containers: mysql-init: Image: registry.cn-beijing.aliyuncs.com/kubegems/kubegems:v1.21.4 Port: Host Port: Args: service migrate --initdata=true Environment Variables from: kubegems-config Secret Optional: false Environment: MYSQL_PASSWORD: <set to the key 'mysql-root-password' in secret 'kubegems-mysql'> Optional: false REDIS_PASSWORD: <set to the key 'redis-password' in secret 'kubegems-redis'> Optional: false ARGO_PASSWORD: <set to the key 'clearPassword' in secret 'argocd-secret'> Optional: false Mounts: Volumes: Events:

─ kubectl logs kubegems-init-v1.21.4-75d28 -n kubegems
2022-09-22 08:52:17.907	warn	config/config.go:90	no config file found or config file format error: Config File "config" Not Found in "[/app /app/config]"
2022-09-22 08:52:17.907	info	config/config.go:107	config from env: MYSQL_ADDR=kubegems-mysql-headless:3306
2022-09-22 08:52:17.907	info	config/config.go:107	config from env: MYSQL_PASSWORD=**********
2022-09-22 08:52:17.907	info	config/config.go:107	config from flag: initdata=true
Error: Error 1045: Access denied for user 'root'@'100.74.135.15' (using password: YES)
Error 1045: Access denied for user 'root'@'100.74.135.15' (using password: YES)
Usage:
  kubegems service migrate [flags]

Flags:
  -h, --help                    help for migrate
      --initdata                insert init data into database
      --mysql-addr string       mysql host addr (default "kubegems-mysql:3306")
      --mysql-database string   database to use (default "kubegems")
      --mysql-password string   mysql password
      --mysql-username string   mysql username (default "root")

**Comment by wimmerX** [comment]
镜像打包有问题？

**Comment by LinkMaq** [comment]
> 2022-09-22 08:52:17.907 info config/config.go:107 config from flag: initdata=true
> Error: Error 1045: Access denied for user 'root'@'100.74.135.15' (using password: YES)
> Error 1045: Access denied for user 'root'@'100.74.135.15' (using password: YES)

是不是重复安装过 kuebgems，如果第一次安装成功后删除，可能是 mysql 的 pvc 没有删除，导致残留了上次安装时的 mysql 密码。建议执行

1. 卸载 kubegems
```
kubectl delete plugin kubegems
```
2.  清除 kubegems 命名空间下的 pvc 卷
```
kubectl  delete pvc --all -n kubegems
```
3. 重新安装 
```
kubectl apply -f kubegems.yaml
```

**Comment by wimmerX** [comment]
丢失了一些预置信息
kubegems-mysql没有被注入DATABASE ENV，导致数据库缺失

> I have no name!@kubegems-mysql-0:/$ env|grep MYSQL
KUBEGEMS_MYSQL_PORT_3306_TCP_PORT=3306
KUBEGEMS_MYSQL_SERVICE_HOST=10.96.2.173
KUBEGEMS_MYSQL_PORT_3306_TCP_PROTO=tcp
KUBEGEMS_MYSQL_PORT=tcp://10.96.2.173:3306
KUBEGEMS_MYSQL_SERVICE_PORT=3306
MYSQL_ROOT_PASSWORD=SQTzn29Zhg
KUBEGEMS_MYSQL_SERVICE_PORT_MYSQL=3306
KUBEGEMS_MYSQL_PORT_3306_TCP=tcp://10.96.2.173:3306
MYSQL_DATABASE=
KUBEGEMS_MYSQL_PORT_3306_TCP_ADDR=10.96.2.173

手动建库后，只有api服务失败，提示缺少表
> kubectl -n kubegems logs kubegems-api-79d4b5bc66-6zc46
2022-09-22 23:29:45.915	warn	config/config.go:90	no config file found or config file format error: Config File "config" Not Found in "[/app /app/config]"
2022-09-22 23:29:45.916	info	config/config.go:107	config from env: APPSTORE_ADDR=http://kubegems-chartmuseum.kubegems:8080
2022-09-22 23:29:45.916	info	config/config.go:107	config from env: ARGO_ADDR=http://kubegems-argo-cd-server:80
2022-09-22 23:29:45.916	info	config/config.go:107	config from env: ARGO_PASSWORD=**********
2022-09-22 23:29:45.916	info	config/config.go:107	config from env: ARGO_USERNAME=admin
2022-09-22 23:29:45.916	info	config/config.go:107	config from env: GIT_ADDR=http://kubegems-gitea-http:3000
2022-09-22 23:29:45.916	info	config/config.go:107	config from env: GIT_PASSWORD=***************
2022-09-22 23:29:45.916	info	config/config.go:107	config from env: GIT_USERNAME=gitea_admin
2022-09-22 23:29:45.916	info	config/config.go:107	config from env: MICROSERVICE_GATEWAYNAMESPACE=kubegems-gateway
2022-09-22 23:29:45.916	info	config/config.go:107	config from env: MICROSERVICE_ISTIOOPERATORNAME=kubegems-istio
2022-09-22 23:29:45.916	info	config/config.go:107	config from env: MYSQL_ADDR=kubegems-mysql-headless:3306
2022-09-22 23:29:45.916	info	config/config.go:107	config from env: MYSQL_PASSWORD=**********
2022-09-22 23:29:45.916	info	config/config.go:107	config from env: REDIS_ADDR=kubegems-redis-headless:6379
2022-09-22 23:29:45.916	info	config/config.go:107	config from env: REDIS_PASSWORD=**********
2022-09-22 23:29:45.916	info	config/config.go:107	config from flag: jwt-cert=/certs/jwt/tls.crt
2022-09-22 23:29:45.916	info	config/config.go:107	config from flag: jwt-key=/certs/jwt/tls.key
2022-09-22 23:29:45.916	info	config/config.go:107	config from flag: system-listen=:8080
2022-09-22 23:29:45.917	info	log/log.go:19	logger level updated	{"level": "debug"}
2022-09-22 23:29:45.917	warn	tracing/tracing.go:37	could not initialize jaeger tracer: no service name provided
2022-09-22 23:29:46.725	info	exporter/exporter.go:127	Enabled collectors
2022-09-22 23:29:46.725	info	exporter/exporter.go:134	collector application
2022-09-22 23:29:46.725	info	exporter/exporter.go:134	collector cluster
2022-09-22 23:29:46.725	info	exporter/exporter.go:134	collector environment
2022-09-22 23:29:46.725	info	exporter/exporter.go:134	collector request
2022-09-22 23:29:46.725	info	exporter/exporter.go:134	collector user
2022-09-22 23:29:46.726	info	exporter/exporter.go:67	prometheus exporter listen on	{"address": ":9100"}
2022-09-22 23:29:46.726	info	pprof/pprof.go:48	debug pprof listen	{"addr": ":6060"}
2022-09-22 23:29:46.731	error	gorm@v1.21.15/callbacks.go:133	Error 1146: Table 'kubegems.tenants' doesn't exist	{"sql": "SELECT * FROM `tenants`", "rows": 0, "latency": "4.922104ms", "source": "model_cache.go:68"}
2022-09-22 23:29:46.731	info	exporter/exporter.go:65	prometheus exporter stopped
2022-09-22 23:29:46.731	info	pprof/pprof.go:46	pprof stopped
Error 1146: Table 'kubegems.tenants' doesn't exist
Error: Error 1146: Table 'kubegems.tenants' doesn't exist

请问，数据库等信息的预置是哪个服务在什么阶段执行的呢？
感谢@LinkMaq 的分享

**Comment by cnfatal** [comment]
建库建表都是由job  kubegems-init-{version} 完成. 没有用 MYSQL_DATABASE 建表。

**Comment by wimmerX** [comment]
> ```
> kubectl delete plugin kubegems
> ```

测试了kubegems v1.21.4 v1.21.3部署失败，最后使用了kind内部署同版本v1.21.1，成功。失败原因皆为job kubegems-init-{version} 执行失败

**Comment by LinkMaq** [comment]
我复现了下上述场景
```
$ k delete -f kubegems.yaml                                                                                                                                                                                               
plugin.plugins.kubegems.io "kubegems" deleted

$ k get pvc
NAME                                 STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-kubegems-gitea-0                Bound         pvc-356e6c09-9ede-4937-88b0-c3a160ebc38b   10Gi       RWO            standard       9m22s
data-kubegems-mysql-0                Bound         pvc-dd736ac5-711a-4cfc-9f10-398c9eda73fc   8Gi        RWO            standard       9m22s
kubegems-chartmuseum                 Terminating   pvc-a575eb0a-bafa-4cbf-9095-0a9ea3bf1bac   10Gi       RWO            standard       9m23s
kubegems-data                        Terminating   pvc-5964e3ee-94eb-488b-9438-5ed3fa595633   6Gi        RWO            standard       9m23s
redis-data-kubegems-redis-master-0   Bound         pvc-847bab80-e0e9-4a09-abd9-fda25aa5c5cb   8Gi        RWO            standard       9m22s
```
删除 kubegems 后，pvc 仍然保持了 mysql、gitea和 redis 的数据卷（为了保留KubeGems数据）
重新部署 kubegems

```
kubectl apply -f kubegems.yaml

NAME                                               READY   STATUS             RESTARTS   AGE   IP            NODE                 NOMINATED NODE   READINESS GATES
kubegems-api-767f9d9594-zgbmg                      0/1     CrashLoopBackOff   3          80s   10.244.0.38   kind-control-plane   <none>           <none>
kubegems-argo-cd-app-controller-6bd8885fdf-cz6qz   1/1     Running            0          80s   10.244.0.27   kind-control-plane   <none>           <none>
kubegems-argo-cd-repo-server-694f9656c6-2hw4c      1/1     Running            0          79s   10.244.0.37   kind-control-plane   <none>           <none>
kubegems-argo-cd-server-5d68bd8859-wlw29           1/1     Running            0          80s   10.244.0.26   kind-control-plane   <none>           <none>
kubegems-chartmuseum-77fb4857cd-whn8j              1/1     Running            0          80s   10.244.0.40   kind-control-plane   <none>           <none>
kubegems-charts-init-v1.22.0-beta.1-6s2g6          0/1     Completed          0          80s   10.244.0.31   kind-control-plane   <none>           <none>
kubegems-dashboard-7c97d486dc-dcg45                1/1     Running            0          80s   10.244.0.28   kind-control-plane   <none>           <none>
kubegems-gitea-0                                   1/1     Running            0          80s   10.244.0.36   kind-control-plane   <none>           <none>
kubegems-init-v1.22.0-beta.1-jj82j                 0/1     CrashLoopBackOff   3          80s   10.244.0.33   kind-control-plane   <none>           <none>
kubegems-msgbus-67cc7b568c-f7kvd                   0/1     CrashLoopBackOff   3          80s   10.244.0.29   kind-control-plane   <none>           <none>
kubegems-mysql-0                                   0/1     Running            0          80s   10.244.0.30   kind-control-plane   <none>           <none>
kubegems-redis-master-0                            1/1     Running            0          79s   10.244.0.34   kind-control-plane   <none>           <none>
kubegems-worker-54468dcc89-qd7mb                   0/1     CrashLoopBackOff   3          80s   10.244.0.39   kind-control-plane   <none>           <none>


$ kubectl logs kubegems-init-v1.22.0-beta.1-jj82j
                                                                                                                                                                           
2022-09-23 04:33:21.599	warn	config/config.go:104	no config file found or config file format error: Config File "config" Not Found in "[/app /app/config]"
2022-09-23 04:33:21.599	info	config/config.go:121	config from env: MYSQL_ADDR=kubegems-mysql-headless:3306
2022-09-23 04:33:21.599	info	config/config.go:121	config from env: MYSQL_PASSWORD=**********
2022-09-23 04:33:21.599	info	config/config.go:121	config from flag: initdata=true
Error: Error 1045: Access denied for user 'root'@'10.244.0.33' (using password: YES)
Usage:
  kubegems service migrate [flags]

Error 1045: Access denied for user 'root'@'10.244.0.33' (using password: YES)
Flags:
  -h, --help                    help for migrate
      --initdata                insert init data into database
      --mysql-addr string       mysql host addr (default "kubegems-mysql:3306")
      --mysql-database string   database to use (default "kubegems")
      --mysql-password string   mysql password
      --mysql-username string   mysql username (default "root")
```

由于 kubegems-init-job 的 `backoffLimit` 设置为10，所以当 job `CrashLoopBackOff` > 10次后，次 job 会标记为`Failed `状态
```
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    meta.helm.sh/release-name: kubegems
    meta.helm.sh/release-namespace: kubegems
  creationTimestamp: "2022-09-23T04:32:34Z"
  labels:
    app.kubernetes.io/component: kubegems
    app.kubernetes.io/instance: kubegems
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubegems
    helm.sh/chart: kubegems-1.21.0
  name: kubegems-init-v1.22.0-beta.1
  namespace: kubegems
  resourceVersion: "4299"
  uid: 7a4307df-2078-460a-8bd9-0406bac95a0e
spec:
  backoffLimit: 10
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 7a4307df-2078-460a-8bd9-0406bac95a0e
  template:
    metadata:
```
---

从 kubegems-init-{version} 这个任务 的 describtion 和日志看起来，导致 job 任务失败的原因是mysql 数据库认证失败引起的。
由于在安装 kubegems 时，数据库密码是通过 helm随机生成的，

所以当出现执行 `kubectl delete  -f kubegems.yaml`时，即为重复安装，需要清除命名空间下的 pvc 数据卷
>提示：kubegems 升级不需要删除数据卷

**Comment by LinkMaq** [comment]
Maybe we should add `forceDelete` field  in `kuebgems.yaml` , witch allow user to delete all manifests of kubegems .@cnfatal

**Comment by wimmerX** [comment]
> 我复现了下上述场景，删除部署成功的 kubegems 版本
> 
> ```
> $ k delete -f kubegems.yaml                                                                                                                                                                                               
> plugin.plugins.kubegems.io "kubegems" deleted
> 
> $ k get pvc
> NAME                                 STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
> data-kubegems-gitea-0                Bound         pvc-356e6c09-9ede-4937-88b0-c3a160ebc38b   10Gi       RWO            standard       9m22s
> data-kubegems-mysql-0                Bound         pvc-dd736ac5-711a-4cfc-9f10-398c9eda73fc   8Gi        RWO            standard       9m22s
> kubegems-chartmuseum                 Terminating   pvc-a575eb0a-bafa-4cbf-9095-0a9ea3bf1bac   10Gi       RWO            standard       9m23s
> kubegems-data                        Terminating   pvc-5964e3ee-94eb-488b-9438-5ed3fa595633   6Gi        RWO            standard       9m23s
> redis-data-kubegems-redis-master-0   Bound         pvc-847bab80-e0e9-4a09-abd9-fda25aa5c5cb   8Gi        RWO            standard       9m22s
> ```
> 
> 删除 kubegems 后，pvc 仍然保持了 mysql、gitea和 redis 的数据卷（为了保留KubeGems数据） 重新部署 kubegems
> 
> ```
> kubectl apply -f kubegems.yaml
> 
> NAME                                               READY   STATUS             RESTARTS   AGE   IP            NODE                 NOMINATED NODE   READINESS GATES
> kubegems-api-767f9d9594-zgbmg                      0/1     CrashLoopBackOff   3          80s   10.244.0.38   kind-control-plane   <none>           <none>
> kubegems-argo-cd-app-controller-6bd8885fdf-cz6qz   1/1     Running            0          80s   10.244.0.27   kind-control-plane   <none>           <none>
> kubegems-argo-cd-repo-server-694f9656c6-2hw4c      1/1     Running            0          79s   10.244.0.37   kind-control-plane   <none>           <none>
> kubegems-argo-cd-server-5d68bd8859-wlw29           1/1     Running            0          80s   10.244.0.26   kind-control-plane   <none>           <none>
> kubegems-chartmuseum-77fb4857cd-whn8j              1/1     Running            0          80s   10.244.0.40   kind-control-plane   <none>           <none>
> kubegems-charts-init-v1.22.0-beta.1-6s2g6          0/1     Completed          0          80s   10.244.0.31   kind-control-plane   <none>           <none>
> kubegems-dashboard-7c97d486dc-dcg45                1/1     Running            0          80s   10.244.0.28   kind-control-plane   <none>           <none>
> kubegems-gitea-0                                   1/1     Running            0          80s   10.244.0.36   kind-control-plane   <none>           <none>
> kubegems-init-v1.22.0-beta.1-jj82j                 0/1     CrashLoopBackOff   3          80s   10.244.0.33   kind-control-plane   <none>           <none>
> kubegems-msgbus-67cc7b568c-f7kvd                   0/1     CrashLoopBackOff   3          80s   10.244.0.29   kind-control-plane   <none>           <none>
> kubegems-mysql-0                                   0/1     Running            0          80s   10.244.0.30   kind-control-plane   <none>           <none>
> kubegems-redis-master-0                            1/1     Running            0          79s   10.244.0.34   kind-control-plane   <none>           <none>
> kubegems-worker-54468dcc89-qd7mb                   0/1     CrashLoopBackOff   3          80s   10.244.0.39   kind-control-plane   <none>           <none>
> 
> 
> $ kubectl logs kubegems-init-v1.22.0-beta.1-jj82j
>                                                                                                                                                                            
> 2022-09-23 04:33:21.599	warn	config/config.go:104	no config file found or config file format error: Config File "config" Not Found in "[/app /app/config]"
> 2022-09-23 04:33:21.599	info	config/config.go:121	config from env: MYSQL_ADDR=kubegems-mysql-headless:3306
> 2022-09-23 04:33:21.599	info	config/config.go:121	config from env: MYSQL_PASSWORD=**********
> 2022-09-23 04:33:21.599	info	config/config.go:121	config from flag: initdata=true
> Error: Error 1045: Access denied for user 'root'@'10.244.0.33' (using password: YES)
> Usage:
>   kubegems service migrate [flags]
> 
> Error 1045: Access denied for user 'root'@'10.244.0.33' (using password: YES)
> Flags:
>   -h, --help                    help for migrate
>       --initdata                insert init data into database
>       --mysql-addr string       mysql host addr (default "kubegems-mysql:3306")
>       --mysql-database string   database to use (default "kubegems")
>       --mysql-password string   mysql password
>       --mysql-username string   mysql username (default "root")
> ```
> 
> 由于 kubegems-init-job 的 `backoffLimit` 设置为10，所以当 job `CrashLoopBackOff` > 10次后，次 job 会标记为`Failed `状态
> 
> ```
> apiVersion: batch/v1
> kind: Job
> metadata:
>   annotations:
>     meta.helm.sh/release-name: kubegems
>     meta.helm.sh/release-namespace: kubegems
>   creationTimestamp: "2022-09-23T04:32:34Z"
>   labels:
>     app.kubernetes.io/component: kubegems
>     app.kubernetes.io/instance: kubegems
>     app.kubernetes.io/managed-by: Helm
>     app.kubernetes.io/name: kubegems
>     helm.sh/chart: kubegems-1.21.0
>   name: kubegems-init-v1.22.0-beta.1
>   namespace: kubegems
>   resourceVersion: "4299"
>   uid: 7a4307df-2078-460a-8bd9-0406bac95a0e
> spec:
>   backoffLimit: 10
>   parallelism: 1
>   selector:
>     matchLabels:
>       controller-uid: 7a4307df-2078-460a-8bd9-0406bac95a0e
>   template:
>     metadata:
> ```
> 
> 从 kubegems-init-{version} 这个任务 的 describtion 和日志看起来，导致 job 任务失败的原因是mysql 数据库认证失败引起的。 由于在安装 kubegems 时，数据库密码是通过 helm随机生成的，
> 
> 所以当出现执行 `kubectl delete -f kubegems.yaml`时，即为重复安装，需要清除命名空间下的 pvc 数据卷
> 
> > 提示：kubegems 升级不需要删除数据卷

1.21.4能装成功么？

**Comment by LinkMaq** [comment]
> 1.21.4能装成功么？

可以的，事实上1.21.x 和 1.22.x在核心的部署流程上是一样的，也可以用上述流程复现问题

```
$ kubectl get pod -o wide                                                                                                                                                                                                                
NAME                                               READY   STATUS      RESTARTS   AGE    IP            NODE                 NOMINATED NODE   READINESS GATES
kubegems-api-58f6bcf789-w9tf8                      1/1     Running     2          114m   10.244.0.42   kind-control-plane   <none>           <none>
kubegems-argo-cd-app-controller-6bd8885fdf-fg22p   1/1     Running     3          114m   10.244.0.37   kind-control-plane   <none>           <none>
kubegems-argo-cd-repo-server-694f9656c6-xkwhd      1/1     Running     1          114m   10.244.0.31   kind-control-plane   <none>           <none>
kubegems-argo-cd-server-5d68bd8859-ntn4t           1/1     Running     3          114m   10.244.0.30   kind-control-plane   <none>           <none>
kubegems-chartmuseum-77fb4857cd-svzcm              1/1     Running     3          114m   10.244.0.40   kind-control-plane   <none>           <none>
kubegems-charts-init-v1.21.4-df887                 0/1     Completed   0          114m   10.244.0.35   kind-control-plane   <none>           <none>
kubegems-dashboard-7bd7d5fbb4-w7r7c                1/1     Running     0          114m   10.244.0.29   kind-control-plane   <none>           <none>
kubegems-gitea-0                                   1/1     Running     0          114m   10.244.0.46   kind-control-plane   <none>           <none>
kubegems-init-v1.21.4-gph5z                        0/1     Completed   0          114m   10.244.0.34   kind-control-plane   <none>           <none>
kubegems-msgbus-65bdbb5dc8-bxw7l                   1/1     Running     2          114m   10.244.0.36   kind-control-plane   <none>           <none>
kubegems-mysql-0                                   1/1     Running     0          114m   10.244.0.44   kind-control-plane   <none>           <none>
kubegems-redis-master-0                            1/1     Running     0          114m   10.244.0.45   kind-control-plane   <none>           <none>
kubegems-worker-6d784c44c6-kk6lz                   1/1     Running     0          114m   10.244.0.43   kind-control-plane   <none>           <none>
```

**Comment by wimmerX** [comment]
好的，我集群托管到tencent tke后运行是正常了，怀疑我之前的自建集群有问题，但是没排查到。今天安装kubegems plugin 指定版本是v1.21.4，但是安装到的是v1.22.0-beta.1。另外，kubegems核心在阿里的镜像有时候拉不到。

**Comment by LinkMaq** [comment]
> 好的，我集群托管到tencent tke后运行是正常了，怀疑我之前的自建集群有问题，但是没排查到。今天安装kubegems plugin 指定版本是v1.21.4，但是安装到的是v1.22.0-beta.1。另外，kubegems核心在阿里的镜像有时候拉不到。

谢谢您反馈，文档中的在线下载的 kubegems需要更新。阿里云的镜像仓库拉取镜像有时候会有 qos 限速，耐心等待就好。
祝您使用愉快😊
