### ISSUE TITLE
After add new clusters , all pods are rebuilt

### ISSUE THREAD

**Issue by wimmerX** [kubegems/kubegems#258]
**What did you do?**
add new cluster
**What did you expect to see?**
normally display cluster setting page
**What did you see instead? Under which circumstances?**
see nothing 
**Environment**

* System information:

   Linux 5.4.119-19-0009.3

* Kubegems version:

	v1.22.0-beta.1

* Kubernetes version:

  1.22.5

* Logs:
```
Normal   Scheduled  11m                  default-scheduler  Successfully assigned kubegems/kubegems-dashboard-756c549fdb-zz9jq to 10.16.20.17
  Normal   Pulling    8m25s (x4 over 11m)  kubelet            Pulling image "registry.cn-beijing.aliyuncs.com/kubegems/dashboard:v1.21.4"
  Warning  Failed     7m55s (x4 over 10m)  kubelet            Error: ErrImagePull
  Warning  Failed     7m43s (x6 over 10m)  kubelet            Error: ImagePullBackOff
  Warning  Failed     6m4s (x5 over 10m)   kubelet            Failed to pull image "registry.cn-beijing.aliyuncs.com/kubegems/dashboard:v1.21.4": rpc error: code = Unknown desc = failed to pull and unpack image "registry.cn-beijing.aliyuncs.com/kubegems/dashboard:v1.21.4": failed to resolve reference "registry.cn-beijing.aliyuncs.com/kubegems/dashboard:v1.21.4": failed to do request: Head "https://registry.cn-beijing.aliyuncs.com/v2/kubegems/dashboard/manifests/v1.21.4": dial tcp 47.95.181.38:443: i/o timeout
  Normal   BackOff    80s (x29 over 10m)   kubelet            Back-off pulling image "registry.cn-beijing.aliyuncs.com/kubegems/dashboard:v1.21.4"
```
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/57867911/192094954-06b0c426-650a-4ab0-8288-aeea1c61c841.png">

**Comment by wimmerX** [comment]
* What I did：
add kubegems itself deployed k8s cluster kubeconfig.

* Doubtful points：
 kubegems-init version has became uncontrollably v1.21.4 from v1.22.0-beta.1

Almost all the pods have been rebuilt，what's the probable cause?🤔

**Comment by LinkMaq** [comment]
The installer of v1.22.0-beta is currently doing some code refactoring and supports updating plugins from the kubegems online repository.  So, you can re-install for a stable version of 1.21.4. 

We're sorry that our mistakes caused you trouble. But you can still wait for our v1.22 , which will be released soon

**Comment by wimmerX** [comment]
Ooops,I see .I encounter other problem in depolying Gems.The one is port-forward error caused me to be unable to log in bashboard，as shown below.
>Handling connection for 8089
  E0925 16:51:46.629355   18707 portforward.go:346] error creating error stream for port 8089 -> 8000: Timeout occurred
  E0925 16:52:07.330296   18707 portforward.go:346] error creating error stream for port 8089 -> 8000: Timeout occurred
  E0925 16:52:07.330331   18707 portforward.go:346] error creating error stream for port 8089 -> 8000: Timeout occurred
  E0925 16:52:07.780789   18707 portforward.go:346] error creating error stream for port 8089 -> 8000: Timeout occurred
  E0925 16:52:07.989836   18707 portforward.go:346] error creating error stream for port 8089 -> 8000: Timeout occurred
  E0925 16:52:08.174634   18707 portforward.go:346] error creating error stream for port 8089 -> 8000: Timeout occurred

pods status in ns Kugegems `kubectl get po -n kubegems`
> 
<img width="775" alt="image" src="https://user-images.githubusercontent.com/57867911/192135932-d69f241e-4388-4ca6-aefe-52cd0207d5e3.png">

Secondly, I have a lots of error pods with  `ImagePullBackOff` ,meanwhile，manual pull images on worker nodes will also report errors such as:
> error pulling image configuration: Get https://registry.cn-beijing.aliyuncs.com/v2/kubegems/argo-rollouts/blobs/sha256:0f5eb3e58bc08e5656ecd7831ddecdfe58b613ce12fff481ef6bb13a9c5180f5: net/http: TLS handshake timeout.
Thirdly,I have add U wehat,please adopt the connect reques. 😬 @LinkMaq

**Comment by wimmerX** [comment]
[https://github.com/kubernetes/kubernetes/issues/74551#issuecomment-910520361](url) has explained  following error possible reason， `ulimit -n 65536` can resolve it.

> E0925 16:52:08.174634 18707 portforward.go:346] error creating error stream for port 8089 -> 8000: Timeout occurred

**Comment by LinkMaq** [comment]
> [https://github.com/kubernetes/kubernetes/issues/74551#issuecomment-910520361](url) has explained following error possible reason， `ulimit -n 65536` can resolve it.
> 
> > E0925 16:52:08.174634 18707 portforward.go:346] error creating error stream for port 8089 -> 8000: Timeout occurred

Thanks for your sharing 💪

**Comment by wimmerX** [comment]
Looking forward to the new stable version release！ 🌅

**Comment by wimmerX** [comment]
Looking forward to the new stable version release！ sunrise
