### ISSUE TITLE
Observability postgresql Invalid type. Expected: string, given: integer

### ISSUE THREAD

**Issue by xiaolaohumen** [kubegems/kubegems#264]
**What did you do?**
      可观测性 ==>接入中心 添加 postgresql 
**What did you expect to see?**
      Create postgresql container and run
**Environment**
       production
* System information:

	Ubuntu 16.04  4.4.0-62-generic

* Kubegems version:

	v1.22.0-beta.0

* Kubernetes version:

	v1.21.14

* Logs:

rpc error: code = Unknown desc = Manifest generation error (cached): `helm template . --name-template 121e069c-sma-sma-sma-sv-psql-obs-scac --namespace default --kube-version 1.21 --values /tmp/7a5c3466-55c0-4b78-b5bc-a3f16f777273 --api-versions acme.cert-manager.io/v1 --api-versions acme.cert-manager.io/v1/Challenge --api-versions acme.cert-manager.io/v1/Order --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1/MutatingWebhookConfiguration --api-versions admissionregistration.k8s.io/v1/ValidatingWebhookConfiguration --api-versions admissionregistration.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1beta1/MutatingWebhookConfiguration --api-versions admissionregistration.k8s.io/v1beta1/ValidatingWebhookConfiguration --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1/CustomResourceDefinition --api-versions apiextensions.k8s.io/v1beta1 --api-versions apiextensions.k8s.io/v1beta1/CustomResourceDefinition --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1/APIService --api-versions apiregistration.k8s.io/v1beta1 --api-versions apiregistration.k8s.io/v1beta1/APIService --api-versions appprotect.f5.com/v1beta1 --api-versions appprotect.f5.com/v1beta1/APLogConf --api-versions appprotect.f5.com/v1beta1/APPolicy --api-versions appprotect.f5.com/v1beta1/APUserSig --api-versions apps/v1 --api-versions apps/v1/ControllerRevision --api-versions apps/v1/DaemonSet --api-versions apps/v1/Deployment --api-versions apps/v1/ReplicaSet --api-versions apps/v1/StatefulSet --api-versions argoproj.io/v1alpha1 --api-versions argoproj.io/v1alpha1/AnalysisRun --api-versions argoproj.io/v1alpha1/AnalysisTemplate --api-versions argoproj.io/v1alpha1/ClusterAnalysisTemplate --api-versions argoproj.io/v1alpha1/Experiment --api-versions argoproj.io/v1alpha1/Rollout --api-versions autoscaling/v1 --api-versions autoscaling/v1/HorizontalPodAutoscaler --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta1/HorizontalPodAutoscaler --api-versions autoscaling/v2beta2 --api-versions autoscaling/v2beta2/HorizontalPodAutoscaler --api-versions batch/v1 --api-versions batch/v1/CronJob --api-versions batch/v1/Job --api-versions batch/v1beta1 --api-versions batch/v1beta1/CronJob --api-versions cert-manager.io/v1 --api-versions cert-manager.io/v1/Certificate --api-versions cert-manager.io/v1/CertificateRequest --api-versions cert-manager.io/v1/ClusterIssuer --api-versions cert-manager.io/v1/Issuer --api-versions certificates.k8s.io/v1 --api-versions certificates.k8s.io/v1/CertificateSigningRequest --api-versions certificates.k8s.io/v1beta1 --api-versions certificates.k8s.io/v1beta1/CertificateSigningRequest --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1/Lease --api-versions coordination.k8s.io/v1beta1 --api-versions coordination.k8s.io/v1beta1/Lease --api-versions crd.projectcalico.org/v1 --api-versions crd.projectcalico.org/v1/BGPConfiguration --api-versions crd.projectcalico.org/v1/BGPPeer --api-versions crd.projectcalico.org/v1/BlockAffinity --api-versions crd.projectcalico.org/v1/ClusterInformation --api-versions crd.projectcalico.org/v1/FelixConfiguration --api-versions crd.projectcalico.org/v1/GlobalNetworkPolicy --api-versions crd.projectcalico.org/v1/GlobalNetworkSet --api-versions crd.projectcalico.org/v1/HostEndpoint --api-versions crd.projectcalico.org/v1/IPAMBlock --api-versions crd.projectcalico.org/v1/IPAMConfig --api-versions crd.projectcalico.org/v1/IPAMHandle --api-versions crd.projectcalico.org/v1/IPPool --api-versions crd.projectcalico.org/v1/KubeControllersConfiguration --api-versions crd.projectcalico.org/v1/NetworkPolicy --api-versions crd.projectcalico.org/v1/NetworkSet --api-versions discovery.k8s.io/v1 --api-versions discovery.k8s.io/v1/EndpointSlice --api-versions discovery.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1beta1/EndpointSlice --api-versions events.k8s.io/v1 --api-versions events.k8s.io/v1/Event --api-versions events.k8s.io/v1beta1 --api-versions events.k8s.io/v1beta1/Event --api-versions extensions/v1beta1 --api-versions extensions/v1beta1/Ingress --api-versions flowcontrol.apiserver.k8s.io/v1beta1 --api-versions flowcontrol.apiserver.k8s.io/v1beta1/FlowSchema --api-versions flowcontrol.apiserver.k8s.io/v1beta1/PriorityLevelConfiguration --api-versions kubegems.io/v1beta1 --api-versions kubegems.io/v1beta1/Environment --api-versions kubegems.io/v1beta1/Tenant --api-versions kubegems.io/v1beta1/TenantNetworkPolicy --api-versions kubegems.io/v1beta1/TenantResourceQuota --api-versions gems.kubegems.io/v1beta1 --api-versions gems.kubegems.io/v1beta1/Environment --api-versions gems.kubegems.io/v1beta1/Tenant --api-versions gems.kubegems.io/v1beta1/TenantGateway --api-versions gems.kubegems.io/v1beta1/TenantNetworkPolicy --api-versions gems.kubegems.io/v1beta1/TenantResourceQuota --api-versions install.istio.io/v1alpha1 --api-versions install.istio.io/v1alpha1/IstioOperator --api-versions integreatly.org/v1alpha1 --api-versions integreatly.org/v1alpha1/Grafana --api-versions integreatly.org/v1alpha1/GrafanaDashboard --api-versions integreatly.org/v1alpha1/GrafanaDataSource --api-versions jaegertracing.io/v1 --api-versions jaegertracing.io/v1/Jaeger --api-versions logging-extensions.banzaicloud.io/v1alpha1 --api-versions logging-extensions.banzaicloud.io/v1alpha1/EventTailer --api-versions logging-extensions.banzaicloud.io/v1alpha1/HostTailer --api-versions logging.banzaicloud.io/v1alpha1 --api-versions logging.banzaicloud.io/v1alpha1/ClusterFlow --api-versions logging.banzaicloud.io/v1alpha1/ClusterOutput --api-versions logging.banzaicloud.io/v1alpha1/Flow --api-versions logging.banzaicloud.io/v1alpha1/Logging --api-versions logging.banzaicloud.io/v1alpha1/Output --api-versions logging.banzaicloud.io/v1beta1 --api-versions logging.banzaicloud.io/v1beta1/ClusterFlow --api-versions logging.banzaicloud.io/v1beta1/ClusterOutput --api-versions logging.banzaicloud.io/v1beta1/Flow --api-versions logging.banzaicloud.io/v1beta1/Logging --api-versions logging.banzaicloud.io/v1beta1/Output --api-versions machinelearning.seldon.io/v1 --api-versions machinelearning.seldon.io/v1/SeldonDeployment --api-versions machinelearning.seldon.io/v1alpha2 --api-versions machinelearning.seldon.io/v1alpha2/SeldonDeployment --api-versions machinelearning.seldon.io/v1alpha3 --api-versions machinelearning.seldon.io/v1alpha3/SeldonDeployment --api-versions models.kubegems.io/v1beta1 --api-versions models.kubegems.io/v1beta1/ModelDeployment --api-versions monitoring.coreos.com/v1 --api-versions monitoring.coreos.com/v1/Alertmanager --api-versions monitoring.coreos.com/v1/PodMonitor --api-versions monitoring.coreos.com/v1/Probe --api-versions monitoring.coreos.com/v1/Prometheus --api-versions monitoring.coreos.com/v1/PrometheusRule --api-versions monitoring.coreos.com/v1/ServiceMonitor --api-versions monitoring.coreos.com/v1/ThanosRuler --api-versions monitoring.coreos.com/v1alpha1 --api-versions monitoring.coreos.com/v1alpha1/AlertmanagerConfig --api-versions nacos.kubegems.io/v1beta1 --api-versions nacos.kubegems.io/v1beta1/ConfigItem --api-versions networking.istio.io/v1alpha3 --api-versions networking.istio.io/v1alpha3/DestinationRule --api-versions networking.istio.io/v1alpha3/EnvoyFilter --api-versions networking.istio.io/v1alpha3/Gateway --api-versions networking.istio.io/v1alpha3/ServiceEntry --api-versions networking.istio.io/v1alpha3/Sidecar --api-versions networking.istio.io/v1alpha3/VirtualService --api-versions networking.istio.io/v1alpha3/WorkloadEntry --api-versions networking.istio.io/v1alpha3/WorkloadGroup --api-versions networking.istio.io/v1beta1 --api-versions networking.istio.io/v1beta1/DestinationRule --api-versions networking.istio.io/v1beta1/Gateway --api-versions networking.istio.io/v1beta1/ServiceEntry --api-versions networking.istio.io/v1beta1/Sidecar --api-versions networking.istio.io/v1beta1/VirtualService --api-versions networking.istio.io/v1beta1/WorkloadEntry --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1/Ingress --api-versions networking.k8s.io/v1/IngressClass --api-versions networking.k8s.io/v1/NetworkPolicy --api-versions networking.k8s.io/v1beta1 --api-versions networking.k8s.io/v1beta1/Ingress --api-versions networking.k8s.io/v1beta1/IngressClass --api-versions networking.kubegems.io/v1beta1 --api-versions networking.kubegems.io/v1beta1/NginxIngressController --api-versions newton.kubegems.io/v1alpha1 --api-versions newton.kubegems.io/v1alpha1/NewtonLabel --api-versions newton.io/v1beta1 --api-versions newton.io/v1beta1/XaasCluster --api-versions newton.io/v1beta1/XaasZone --api-versions newton.io/v1beta1/XaasZoneLimitRange --api-versions newton.io/v1beta1/XaasZoneResourceQuota --api-versions node.k8s.io/v1 --api-versions node.k8s.io/v1/RuntimeClass --api-versions node.k8s.io/v1beta1 --api-versions node.k8s.io/v1beta1/RuntimeClass --api-versions plugins.kubegems.io/v1alpha1 --api-versions plugins.kubegems.io/v1alpha1/Installer --api-versions plugins.kubegems.io/v1beta1 --api-versions plugins.kubegems.io/v1beta1/Installer --api-versions plugins.kubegems.io/v1beta1/Plugin --api-versions policy/v1 --api-versions policy/v1/PodDisruptionBudget --api-versions policy/v1beta1 --api-versions policy/v1beta1/PodDisruptionBudget --api-versions policy/v1beta1/PodSecurityPolicy --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1/ClusterRole --api-versions rbac.authorization.k8s.io/v1/ClusterRoleBinding --api-versions rbac.authorization.k8s.io/v1/Role --api-versions rbac.authorization.k8s.io/v1/RoleBinding --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions rbac.authorization.k8s.io/v1beta1/ClusterRole --api-versions rbac.authorization.k8s.io/v1beta1/ClusterRoleBinding --api-versions rbac.authorization.k8s.io/v1beta1/Role --api-versions rbac.authorization.k8s.io/v1beta1/RoleBinding --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1/PriorityClass --api-versions scheduling.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1beta1/PriorityClass --api-versions security.istio.io/v1beta1 --api-versions security.istio.io/v1beta1/AuthorizationPolicy --api-versions security.istio.io/v1beta1/PeerAuthentication --api-versions security.istio.io/v1beta1/RequestAuthentication --api-versions snapshot.storage.k8s.io/v1 --api-versions snapshot.storage.k8s.io/v1/VolumeSnapshot --api-versions snapshot.storage.k8s.io/v1/VolumeSnapshotClass --api-versions snapshot.storage.k8s.io/v1/VolumeSnapshotContent --api-versions snapshot.storage.k8s.io/v1beta1 --api-versions snapshot.storage.k8s.io/v1beta1/VolumeSnapshot --api-versions snapshot.storage.k8s.io/v1beta1/VolumeSnapshotClass --api-versions snapshot.storage.k8s.io/v1beta1/VolumeSnapshotContent --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1/CSIDriver --api-versions storage.k8s.io/v1/CSINode --api-versions storage.k8s.io/v1/StorageClass --api-versions storage.k8s.io/v1/VolumeAttachment --api-versions storage.k8s.io/v1beta1 --api-versions storage.k8s.io/v1beta1/CSIDriver --api-versions storage.k8s.io/v1beta1/CSINode --api-versions storage.k8s.io/v1beta1/CSIStorageCapacity --api-versions storage.k8s.io/v1beta1/StorageClass --api-versions storage.k8s.io/v1beta1/VolumeAttachment --api-versions telemetry.istio.io/v1alpha1 --api-versions telemetry.istio.io/v1alpha1/Telemetry --api-versions v1 --api-versions v1/ConfigMap --api-versions v1/Endpoints --api-versions v1/Event --api-versions v1/LimitRange --api-versions v1/Namespace --api-versions v1/Node --api-versions v1/PersistentVolume --api-versions v1/PersistentVolumeClaim --api-versions v1/Pod --api-versions v1/PodTemplate --api-versions v1/ReplicationController --api-versions v1/ResourceQuota --api-versions v1/Secret --api-versions v1/Service --api-versions v1/ServiceAccount --include-crds` failed exit status 1: Error: values don't meet the specifications of the schema(s) in the following chart(s): prometheus-postgres-exporter: - config.datasource.port: Invalid type. Expected: string, given: intege

**Comment by LinkMaq** [comment]
fixed at https://github.com/kubegems/appstore-charts/commit/224868a7d92af2f627551264675c484804b9a6a6

@xiaolaohumen Thanks for your report ! 💪🏻
