### ISSUE TITLE
go: github.com/go-check/check@v1.0.0-20180628173108-788fd7840127: invalid pseudo-version: major version without preceding tag must be v0, not v1 go: github.com/argoproj/argo-rollouts@v1.1.1 requires 	github.com/argoproj/notifications-engine@v0.2.1-0.20210525191332-e8e293898477 requires 	gomodules.xyz/notify@v0.1.0 requires 	github.com/appscode/go@v0.0.0-20190808133642-1d4ef1f1c1e0 requires 	github.com/flosch/pongo2@v0.0.0-20181225140029-79872a7b2769 requires 	github.com/go-check/check@v1.0.0-20180628173108-788fd7840127: invalid pseudo-version: major version without preceding tag must be v0, not v1

### ISSUE THREAD

**Issue by taitaking** [kubegems/kubegems#274]
go: github.com/go-check/check@v1.0.0-20180628173108-788fd7840127: invalid pseudo-version: major version without preceding tag must be v0, not v1
go: github.com/argoproj/argo-rollouts@v1.1.1 requires
	github.com/argoproj/notifications-engine@v0.2.1-0.20210525191332-e8e293898477 requires
	gomodules.xyz/notify@v0.1.0 requires
	github.com/appscode/go@v0.0.0-20190808133642-1d4ef1f1c1e0 requires
	github.com/flosch/pongo2@v0.0.0-20181225140029-79872a7b2769 requires
	github.com/go-check/check@v1.0.0-20180628173108-788fd7840127: invalid pseudo-version: major version without preceding tag must be v0, not v1

**Comment by pepesi** [comment]
duplicated with this one https://github.com/kubegems/kubegems/issues/276
