### ISSUE TITLE
ARM support for kubegems server and agent

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#293]
**Is your feature request related to a problem? Please describe.**
kubegems  is not available for ARM architecture

**Describe the solution you'd like**
kubegems available on ARM architecture

**Comment by cnfatal** [comment]
- Add kubegems support for arm on 0d93cda71bd7168f4babd15d74c9e9c273c32d3f
- Add kubegems kubectl arm support on da25b8e13bb964ec9b26ac8218714cf5086b25e9
