### ISSUE TITLE
cannot create directory '/bitnami/mysql/data': Permission denied

### ISSUE THREAD

**Issue by JosonJiang** [kubegems/kubegems#306]
基于原有 K8s 服务 pod 运行如下

`

> NAME                                               READY   STATUS             RESTARTS      AGE
> kubegems-api-578796cbb8-lrdtb                      0/1     Init:0/1           0             7m23s
> kubegems-argo-cd-app-controller-55479d7b7f-cctkj   1/1     Running            0             7m23s
> kubegems-argo-cd-repo-server-644b9bdccd-4l25r      1/1     Running            0             7m23s
> kubegems-argo-cd-server-74b794fcd5-9tslm           1/1     Running            0             7m23s
> kubegems-chartmuseum-7584f779ff-7r27v              1/1     Running            0             7m23s
> kubegems-charts-init-v1.22.0-beta.2-vtdn5          0/1     Completed          0             7m23s
> kubegems-dashboard-db546988b-h2www                 1/1     Running            0             7m23s
> kubegems-gitea-0                                   1/1     Running            0             7m23s
> kubegems-msgbus-9f5f47c89-xmf8m                    0/1     Init:0/1           0             7m23s
> kubegems-mysql-0                                   0/1     CrashLoopBackOff   6 (99s ago)   7m23s
> kubegems-redis-master-0                            1/1     Running            0             7m23s
> kubegems-worker-6fbf65b899-mj25x                   0/1     Init:0/1           0             7m23s

`

**kubegems-mysql**

`

> kubectl -n kubegems logs kubegems-mysql-0
> mysql 03:56:17.87
> mysql 03:56:17.89 Welcome to the Bitnami mysql container
> mysql 03:56:17.89 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
> mysql 03:56:17.90 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
> mysql 03:56:17.90
> mysql 03:56:17.90 INFO  ==> ** Starting MySQL setup **
> mysql 03:56:17.96 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
> mysql 03:56:17.97 INFO  ==> Initializing mysql database
> mkdir: cannot create directory '/bitnami/mysql/data': Permission denied

`

**Comment by LinkMaq** [comment]
@JosonJiang  k8s 用的什么版本？ 看起来分配给 mysql 的 pvc 权限不太对。麻烦提供一下详细的信息

**Comment by JosonJiang** [comment]
kubectl version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.

**Client Version**: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"windows/amd64"}

Kustomize Version: v4.5.4
**Server Version:** version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:18:48Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}

**kubectl version --output=yaml**

**clientVersion**:
  buildDate: "2022-05-24T12:26:19Z"
  compiler: gc
  gitCommit: 3ddd0f45aa91e2f30c70734b175631bec5b5825a
  gitTreeState: clean
  gitVersion: v1.24.1
  goVersion: go1.18.2
  major: "1"
  minor: "24"
  platform: windows/amd64
kustomizeVersion: v4.5.4
**serverVersion**:
  buildDate: "2022-05-24T12:18:48Z"
  compiler: gc
  gitCommit: 3ddd0f45aa91e2f30c70734b175631bec5b5825a
  gitTreeState: clean
  gitVersion: v1.24.1
  goVersion: go1.18.2
  major: "1"
  minor: "24"
  platform: linux/amd64

windows 10 下的  Docker Desktop 安装的 k8s 单机版



又把它装到  Centos7 下面 没有出现这个问题，但是新的问题又出现了：无法加入集群，连接服务器失败

![image](https://user-images.githubusercontent.com/3362073/199366880-bcd70785-c059-43ba-bec1-1f1a73ef858c.png)

![image](https://user-images.githubusercontent.com/3362073/199367053-3c59987a-7a62-4951-ada0-bc7b628a5e05.png)

**Comment by LinkMaq** [comment]
先解决第二个问题，无法加入集群，看日志是 kubgems-api 这个容器里面解析不到 `lb.kubesphere.local` 这个域名，这应该是个外部域名，coredns 解析不了。你可以把 kubeconfig 里面的`cluster.server `改成 `kubernetes.default:443`，这样添加本集群直接利用集群内部 dns 解析了。

第一个问题，windows 下使用 kind 安装kubegems 目录权限我需要去复现下

**Comment by LinkMaq** [comment]
@JosonJiang  我没有复现此问题，升级下 docker engine 试下
![image](https://user-images.githubusercontent.com/2688646/199395714-0549b00a-f645-41d5-a6b3-6a38989eba52.png)

**Comment by JosonJiang** [comment]
windows 下 我卸载后重新 安装kubegems 已经可以了；但是 Liunx那个还没解决 问题大概是因为 https://lb.kubesphere.local:6443/ 这个访问不了 稍后网络方面处理下再测试；

谢谢回复，一直关注着 哈 比以前安装简单多了
