### ISSUE TITLE
try login registry: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by willzhang** [kubegems/kubegems#328]
**What did you do?**
add docker registry
**What did you expect to see?**
add success
**What did you see instead? Under which circumstances?**
add with error logs
```
try login registry: invalid character '<' looking for beginning of value
```
**Environment**

* System information:

	insert output of `uname -srm` here

* Kubegems version:

v1.22.0

* Kubernetes version:
v1.25.3

* Logs:
![image](https://user-images.githubusercontent.com/33590311/204072966-de33f9dd-d7aa-4eaa-9ad0-3d6e667fd231.png)

**Comment by LinkMaq** [comment]
This registry enabled https？

**Comment by willzhang** [comment]
no ,it's http

**Comment by LinkMaq** [comment]
1.23 版本修复
