### ISSUE TITLE
[Doc] Development  handbook for the Alert channel

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#385]

**Comment by jojotong** [comment]
Already exist: https://github.com/kubegems/alertproxy/blob/main/DEVELOPMENT.md

**Comment by LinkMaq** [comment]
> Already exist: https://github.com/kubegems/alertproxy/blob/main/DEVELOPMENT.md

Nice, pls sync it to https://www.kubegems.io/docs/expand/development/alert-channel

**Comment by LinkMaq** [comment]
> Already exist: https://github.com/kubegems/alertproxy/blob/main/DEVELOPMENT.md

@jojotong 
Nice work ! pls sync to https://www.kubegems.io/docs/expand/development/alert-channel
