### ISSUE TITLE
The api which updates the rels betweteen project and user doesn't work

### ISSUE THREAD

**Issue by Answerlord** [kubegems/kubegems#405]
**What did you do?**

I use the api which url is `/v1/project/{project_id}/user/{user_id}` by `put` method to update the rels between project and user.

**What did you expect to see?**

I expect to see the http response shows ok and the rels in database have been updated.

**What did you see instead? Under which circumstances?**

The http response shows ok but the rels rels in database don't be update.

**Environment**

* System information:

	centos 6.7 64bit

* Kubegems version:

	1.2

* Kubernetes version:

	insert output of `kubectl version` here (if relevant to the issue)

* Logs:
```
insert Kubegems logs relevant to the issue here
```

**Something maybe helpful**

I read your source code which works on the api,there seems to be an error in your code in ``pkg/service/handlers/project/handler_project.go`` line 346-358

```
var rel models.ProjectUserRels  
if err := c.BindJSON(&rel); err != nil {  
   handlers.NotOK(c, err)  
   return  
}  
if err := h.GetDB().First(&rel, "project_id = ? and user_id = ?", c.Param(PrimaryKeyName), c.Param("user_id")).Error; err != nil {  
   handlers.NotOK(c, fmt.Errorf("不可以修改不存在的 \"项目-用户\" 关系"))  
   return  
}  
if err := h.GetDB().Save(&rel).Error; err != nil {  
   handlers.NotOK(c, err)  
   return  
}
```
you use the variable that named `rel` to parse the json and get the gorm result at same time,and then you use the variable to update the rel of project and user.This means that you use the old data in the database to update, instead of using the data passed in by the user in json.I think this is the cause of this bug.I hope this maybe helpful.

**Comment by pepesi** [comment]
I see...
Not only this problem.
If the URL path parameter is not matched with the body, the save would cause an error result.

Thanks. Fixed soon

**Comment by Answerlord** [comment]
> I see... Not only this problem. If the URL path parameter is not matched with the body, the save would cause an error result.
> 
> Thanks. Fixed soon

Thanks for repling.I'm looking forward to it.

**Comment by pepesi** [comment]
This fix will release with version 1.23.
Which version are you using now? From your description, We have not released a version whose name is v1.2.

**Comment by Answerlord** [comment]
> 

release 1.20

**Comment by pepesi** [comment]
Change the api image to this one now `kubegems/kubegems:v1.20.0-beta5`

**Comment by Answerlord** [comment]
> Change the api image to this one now `kubegems/kubegems:v1.20.0-beta5`

Thank you very much,but my workmate told me they are using `v1.22` now,would you mind to merge this change to `release-1.22`? so that we can make image by ourselves(we modified part of the code according to our needs).

**Comment by pepesi** [comment]
I cherry-picked that commit to release-1.22 just now, After action finished, It should be OK.

**Comment by Answerlord** [comment]
> I cherry-picked that commit to release-1.22 just now, After action finished, It should be OK.

thanks a lot

**Comment by pepesi** [comment]
New image tag: v1.22.4
