### ISSUE TITLE
[AI-Store] Both `http` and `grpc` ports are supported  in modeldeploy gateway

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#408]

**Comment by cnfatal** [comment]
- nginx ingress 只支持使用TLS 和不同的 hostname 进行分发
- 不支持 plaintext 在 80 端口同时支持 http 和 grpc  <https://github.com/kubernetes/ingress-nginx/issues/3897>
- 不支持在grpc时使用 basepath, <https://github.com/grpc/grpc/issues/14900>
