### ISSUE TITLE
Plugging in the AppStore && ArgoCD

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#409]

**Comment by cnfatal** [comment]
TODO:
- [ ] a migrate needed, gitea address changed from `http://kubegems-gitea-http:3000` to `http://kubegems-apps-gitea-http:3000`
- [ ] migrate old gitea data  to newly gitea

**Comment by cnfatal** [comment]
Add a switch in kubegems plugin to disable app center relates.
