### ISSUE TITLE
💣 Cann't update alertrules after channel has deleted

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#412]
![Image](https://user-images.githubusercontent.com/2688646/215252054-2984f8c7-c081-49d2-9939-8ef8d150dc4c.png)

expose an error
>failed to get channel by receiver: {0xc00783ee10 1h {alert-id-22 [] [] [] [{0xc0123166c9 0xc0113ac270 nil <nil> 0}] [] [] [] []} 2}: channel: 22 not found

**Comment by jojotong** [comment]
It has been resolved after 1.23 upgade.
