### ISSUE TITLE
 Permission denied kubegems-mysql  CrashLoopBackOff  

### ISSUE THREAD

**Issue by JosonJiang** [kubegems/kubegems#434]
``
kubectl get pods -n kubegems

NAME                                               READY   STATUS             RESTARTS       AGE
kubegems-api-5c84b7f8c7-lr9gz                      0/1     Init:0/1           0              14h
kubegems-argo-cd-app-controller-65498849f6-rrlwz   1/1     Running            0              14h
kubegems-argo-cd-repo-server-758d6f4787-cswlk      1/1     Running            0              14h
kubegems-argo-cd-server-6cc598df8d-6gldk           1/1     Running            0              14h
kubegems-chartmuseum-5797847bfd-tqttm              1/1     Running            0              14h
kubegems-charts-init-v1.23.1-9jw95                 0/1     Completed          0              14h
kubegems-dashboard-79f59679b4-s85kk                1/1     Running            0              14h
kubegems-gitea-0                                   1/1     Running            0              14h
kubegems-msgbus-554dc555c4-xtd2c                   0/1     Init:0/1           0              14h
kubegems-mysql-0                                   0/1     CrashLoopBackOff   16 (26s ago)   14h
kubegems-redis-master-0                            1/1     Running            0              14h
kubegems-worker-66b4fb598d-t65jz                   0/1     Init:0/1           0              14h

kubectl logs kubegems-mysql-0 -n kubegems -f
 
![image](https://user-images.githubusercontent.com/3362073/217119165-a653c425-c5be-4a89-a3a8-f6cf87076fcf.png)

mkdir: cannot create directory '/bitnami/mysql/data': Permission denied

首次安装成功；现在报错无权限 该如何处理，重新安装过还是这样。windows11 管理员权限 cmd命令行下执行安装的；

帮忙看下什么问题谢谢了

**Comment by LinkMaq** [comment]
@JosonJiang  你用的什么storageclass？

**Comment by JosonJiang** [comment]
> @JosonJiang 你用的什么storageclass？

kubectl get sc -n kubegems
NAME                   PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path (default)   docker.io/local-path   Delete          WaitForFirstConsumer   true                   3h6m

好像是这个 自动创建的吧

**Comment by JosonJiang** [comment]
我把所有的卸载了 重新再装一次正常了；先关闭这个吧

**Comment by JosonJiang** [comment]
![image](https://user-images.githubusercontent.com/3362073/217974481-34f5d7ab-ffdf-465e-96df-2fc1c6c8f3c1.png)

问题又出现了，重启就这样；实在不想重新安装

**Comment by JosonJiang** [comment]
这个问题自己解决了下 具体参考
https://github.com/bitnami/charts/issues/8565


直接修改这个 
![Uploading image.png…]


kubectl delete -f kubegems-MySQL-Statefulset.yml 
kubectl apply -f kubegems-MySQL-Statefulset.yml
