### ISSUE TITLE
使用腾讯云部署的时候使用sc生成pvc报错

### ISSUE THREAD

**Issue by BruceChinese** [kubegems/kubegems#437]
使用腾讯云来部署的时候使用sc来生成pvc的时候报错, 腾讯云sc生成的pvc最小是10G 麻烦问下这个怎么修改pvc的磁盘大小

![image](https://user-images.githubusercontent.com/12492229/217179472-5fc554d7-dec6-47fa-a8f0-297f64d97b6d.png)

**Comment by cnfatal** [comment]
```yaml
```

**Comment by BruceChinese** [comment]
这个每个都要写一遍是挺麻烦的,建议这边咱们可以在values里提供参数,这样直接写就很方便了

**Comment by LinkMaq** [comment]
closing issues ，any discussion can be reopened.
