### ISSUE TITLE
default image repository of gateway cannot be changed

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#45]
**What did you do?**
采用 kubegems-installer 安装kubegems，使用全局的 repository 为阿里云（registry.cn-beijing.aliyuncs.com/kubegems），但是在安装完成后，位于命名空间`gemcloud-gateway-system`的默认网关`default-gateway` 镜像仍然是 `kubegems/nginx-ingress:1.11.1`

**What did you see instead? Under which circumstances?**
`default-gateway`的镜像地址应该跟随全局的 repository 变化

**Environment**

* System information:

    ALIYUN-ACK

* Kubegems version:

    v1.20.0-beta.1

* Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-aliyun.1", GitCommit:"d966b365d87fb2783deab0d244047d340f1be146", GitTreeState:"clean", BuildDate:"2022-01-19T01:10:01Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jojotong** [comment]
Fixed at https://github.com/kubegems/kubegems/commit/bcaeeee9258dde1df8dce4db9d9091deb62fb91e and installer https://github.com/kubegems/installer-operator/pull/17
