### ISSUE TITLE
支持填写多个master地址并进行负载均衡访问

### ISSUE THREAD

**Issue by kinbod** [kubegems/kubegems#466]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![b2ffc4d6fce2cec87f0563d28bf804a](https://user-images.githubusercontent.com/8268021/234773702-9fedb03a-6c94-4490-986b-3d7a95cb5af1.jpg)

**Comment by LinkMaq** [comment]
这是由kubeconfig实现，可以自行在apisierver前面部署loadbalancer来实现负载均衡

**Comment by LinkMaq** [comment]
closing issues ，any discussion can be reopened.
