### ISSUE TITLE
您好，请问可否集成到CICD持续集成上面来？

### ISSUE THREAD

**Issue by cfy3133** [kubegems/kubegems#471]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LinkMaq** [comment]
您好，在再跟一些团队和公司沟通的时发现大多公司都已有适合自己 devops 流程，kuebgems 无意引入 ci 部分去变更用户的已有的流程，平台只为k8s做集中的 manifest 管理以及 cd 部分。kuebgems提供 api 来实现应用部署，最终作为 devops 中的一环来集成到用户已有流程当中。 您可以加入我们用户社群看下其他用户有没有类似需求

**Comment by cfy3133** [comment]
好滴，谢谢您

**Comment by LinkMaq** [comment]
closing issues ，any discussion can be reopened.
