### ISSUE TITLE
 logging Plugin Error 

### ISSUE THREAD

**Issue by liyongxian** [kubegems/kubegems#475]
**Environment**

* System information:

* Kubegems version:
 v1.23.8

* Kubernetes version:
  1.25.X
kubernetes after 1.25 does not support psp,please update  chart of logging-operator.
Thanks.

* Logs:
plugin kubegems-logging/logging-operator: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
![image](https://github.com/kubegems/kubegems/assets/18571576/d171dfbb-be7f-4af8-8fc2-bd9f6148e781)

**Comment by LinkMaq** [comment]
#473
