### ISSUE TITLE
logging ERROR

### ISSUE THREAD

**Issue by liyongxian** [kubegems/kubegems#476]
**What did you do?**
**Install logging Plugins**
**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Kubegems version:
 **v1.23.8**
	insert output of `kubegems --version` here

* Kubernetes version:
**v1.25.6**
	insert output of `kubectl version` here (if relevant to the issue)

* Logs:
![image](https://github.com/kubegems/kubegems/assets/18571576/5bcf1257-7d12-4a2e-94bb-9b71926f9ba6)

**Comment by LinkMaq** [comment]
在对应的k8s集群下面执行`kubectl get flow -A`看下是是否存在match为空的配置

**Comment by liyongxian** [comment]
在 kubernetes 1.24 版本上部署kubegems，没有这个问题。
