### ISSUE TITLE
项目运维无法正确创建应用编排，权限校验存在bug

### ISSUE THREAD

**Issue by tyut22316** [kubegems/kubegems#478]
**What did you do?**
项目运维角色执行应用编排AppManifests创建，显示无权限获取该数据
![image-20230912172238869](https://github.com/kubegems/kubegems/assets/42953016/d529e4c4-b7c7-4461-a00a-a19885f1fb32)
此时检查接口返回结果
![image-20230912172339174](https://github.com/kubegems/kubegems/assets/42953016/1c092e08-cb76-4060-a888-3e7adb1583b1)
此时看到调用了list Manifests接口 并返回403 
这里明显不应该调用List接口 应该是create接口 详细内容等会截图
![image-20230912172351086](https://github.com/kubegems/kubegems/assets/42953016/2c40e14d-fd72-411f-84cf-056cd9331666)
![image-20230912172416907](https://github.com/kubegems/kubegems/assets/42953016/e8280d58-f483-4574-ae48-1f7ef03258ae)

查看报错返回 没有权限操作项目  这里是去执行了checkByProjectId 后续截图

<img width="1020" alt="image-20230912173052246" src="https://github.com/kubegems/kubegems/assets/42953016/1c2b3dae-6ec4-423b-8409-1ee8902206d6">
可以看到实际先去调用了listManifest 这里的权限判断和CreateManifest出现了不一致

<img width="512" alt="image-20230912173103524" src="https://github.com/kubegems/kubegems/assets/42953016/c058ff9a-8528-4c45-8eda-a84e6cb54a06">
当前场景下 checkCanDeployEnviroment 作为项目运维角色 应该具备createManifest权限 

这里推断使用项目管理员，即拥有list权限 才可以正常创建
改用项目管理员验证猜想
![image-20230912172150211](https://github.com/kubegems/kubegems/assets/42953016/7fd8f47e-9501-436e-b595-5776d922f4f5)

验证成功。

bug：项目运维具有创建权限，却无法创建

**Comment by LinkMaq** [comment]
@cnfatal  你看下这里呢

**Comment by cnfatal** [comment]
已修复，会随 1.24.0 发布
