### ISSUE TITLE
你好，是否能支持DeepFlow可观测性平台的集成(https://github.com/deepflowio/deepflow)

### ISSUE THREAD

**Issue by cfy3133** [kubegems/kubegems#479]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LinkMaq** [comment]
面前暂无计划，感谢关注🙏

**Comment by cfy3133** [comment]
好的吧，谢谢您
