### ISSUE TITLE
Support k8s gateway api in tenant gateway.

### ISSUE THREAD

**Issue by sunlintong** [kubegems/kubegems#5]
We need to consider using  k8s gateway api in tenant gateway.   

Now we use custom TenantGateway CRD to describe kubegems api gateway. But k8s gateway api v1ahpha2 has been released last year(refer to https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.4.0).  

Because nginx hasn't implement gateway api, we can choose one of the following ways:
- Choose one of implemention at https://github.com/kubernetes-sigs/gateway-api/blob/master/site-src/implementations.md. 
- Wait for nginx's implemention, at https://github.com/kubernetes/ingress-nginx/issues/7517

**Comment by LinkMaq** [comment]
Any further updates? @jojotong

**Comment by jojotong** [comment]
Waiting for ingress-nginx's implement plan.
