### ISSUE TITLE
[Bugs] Some issues of normal users access permission 

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#51]
我整理了 4 个关于普通用户权限问题，在KubeGems v1.20.0-beta.2的测试中没有覆盖到。

KubeGems 版本： v1.20.0-beta.2
Kubernetes版本： v1.18.16
Installer 版本：v1.20.0-beta.2

**bug1**

当普通用户加入虚拟空间后，该用户无法进入虚拟空间。接口返回403 错误。内容如下：

```
{"Message":"forbidden","Data":"当前用户没有虚拟空间的操作权限","ErrorData":null}
```

**期望**

普通用户具备访问虚拟空间的只读权限

**bug2**

 普通用户在可观察性中，无法列出 prometheus查询语句模板

```
{"Message":"forbidden","Data":"只有系统管理员可以执行当前操作","ErrorData":null}
```

**期望**

普通用户具备指标查询权限

**bug3**

 普通用户在可观察性中，进入“链路跟踪” 页面无响应

**bug4**

普通用户在可观察性中，「日志采集器」、「日志路由器」和「监控采集器」页面无法列出集群列表。

> 虽然此部分功能属于v1.21版本的 feature，我建议将此部分功能在v1.20.0版本中下线

**Comment by jojotong** [comment]
fixed bug2 at fd6e2fc
