### ISSUE TITLE
[Bugs] Can't upgrade kubegems_local versions on KubeGems plugins management

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#62]
**What did you do?**

当 KubeGems Centrol 升级后，在平台的【插件管理】中的  "kubegems_local" 组件并未出现升级按钮

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/2688646/167368731-f2b98b43-99ed-4f47-b177-78fa0ce3bf5e.png">

**What did you see instead? Under which circumstances?**

组件管理中支持升级操作

**Environment**

- System information:

ALIYUN-ACK

- Kubegems version:

v1.20.0-beta.2

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-aliyun.1", GitCommit:"757dfe7e010afcfa31591df65f26b4b80540975e", GitTreeState:"clean", BuildDate:"2022-04-20T09:01:29Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by chenshunliang** [comment]
This bug caused by installor upgraded changed plugin name, but dashboard not sync. Fixed at  https://github.com/kubegems/dashboard/pull/55
