### ISSUE TITLE
[Bugs]The timestamp of log context is 0.1ms faster than actual.

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/kubegems#63]
**What did you do?**

在【可观测性】中，使用日志查看器中查询 “堆栈类“的日志报错信息时，如果采用正则表达式后查看“日志上下文“，即可复现此问题。

**What did you see instead? Under which circumstances?**

日志实际的时间戳：1652090804397327046
KubeGems 上下文中的时间戳：1652090804397427200
![image](https://user-images.githubusercontent.com/2688646/167434431-6a66d3d7-a38d-4dbb-bf5f-a6959d2ee82c.png)

这里产生了大约 0.1ms的延迟，导致日志上下文不能匹配。
https://github.com/kubegems/dashboard/blob/11769f0439c2ef48c1a571774a746ec01fdfebdc/src/views/observe/log/viewer/components/LogContext.vue#L109

```js
 async handleLoadPreview () {
      this.loading.preview = true
      const timestamp = (this.items.preview.length ? this.items.preview[0].timestamp : this.params.timestamp).toString()
      const start = new Date(parseInt(timestamp.substr(0, 13)) - 1000 * 60 * 60 * 3).getTime() + '000000'
      const end = (parseInt(timestamp) - 100000).toString()
      const data = await this.getLogContext(start, end)
      this.items.preview = [...data, ...this.items.preview]
      this.loading.preview = false
    },
```
时间戳延迟 0.1ms 是为了获取上下文日志时，避免获取当前时间戳下的重复日志。大多数情况下 0.1ms 影响并不会太大，当时对于程序的异常堆栈日志，更多是同一时间打印的出来的，`如果堆栈日志大于 10 行，即会出现此问题`。

**Environment**

- System information:

ALIYUN-ACK

- Kubegems version:

v1.20.0-beta.2

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-aliyun.1", GitCommit:"757dfe7e010afcfa31591df65f26b4b80540975e", GitTreeState:"clean", BuildDate:"2022-04-20T09:01:29Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by chenshunliang** [comment]
This bug caused by the timestamp value and fixed at https://github.com/kubegems/dashboard/pull/57
